language: python
jobs:
  include:
  - services: docker
  - os: osx
    language: shell
  - os: windows
    language: shell
    before_install:
    - choco install python --version 3.8.0
    - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
env:
  global:
  - secure: J46vbryvhePxvnUcS4nEZos9mmFscJ80XLAiKIwUxVwR7nYDwoxIooWK+n2G+9surozu6CRhLtNDGih0iUEwK12S2+AMv6KLFTU9ZDDZkI3eKJsjUrBIME4hLf37UZhfw0qtdPApkdLLx761lxP1t2t9VNODQfyB92pUhf9WOh5e1jh6EuYT3ru4q3NsJYYILpIseBTGzF57jOxZK3bMqlt/CMk26XlmfnFf0obIF8zBmYzMhxRqFqkq37KnnYdOSOM9npxjiH14hkMUUuOGlR4waF1tD38amWaHf/LjWGoNf7vnP0RYeh2lBJgZDiR30S7JRjEaVDRAnt4gtplsSeM5bwQ2WMk4YsMaPDdlbNI2d8NKtJKk5NE0MATFJ/E4lltekT03OPnKkA0p8I98vkT7r+vvq5h0JAmeRltIz8+c78myNkNFLprG4vyur53NXsivgQLwYp2R9kxF2PDIoWypJ5vvruJmSB3dKYwVuwIJbpkfq38LjK/06TevKTh9aO8TfylvREXmGO2reWJEPKvfamJsb/vEDodeNibOPFQnAW/U/CW5f2KglGnuDnHGU0NyJP/t/UhvKxL/e2/8dtRFSAqaqkSY2sY4t/9rZ+FXEUTDfsPU17I9BVmQDkB5M5l+vN4JrEOU4K7DkI1jv2N/fi3bo88K3+O9TnVPEYs=
  - secure: L7Px4PJUSmNKHVfcDdiOEh+rM8uf6/IV/RcIIkF7urisGXuMFHSUUViZN3hH7+qazGPBKed5uFyN3MgpMkjudvQVkGsNqTPbhNg8rCZycun3jUWiK479iRsARnXhTZZ3EnTIX0uvV/OeUJMDtf1vUOPGpTfVw1bcJt3/sKtunacXGL4sO01xq5ZRJHt5/ZQ2ZewmtosVnZPCH8UThnWm8TM0kcRlKPaamq0oUIkUVWIEMNNEpoD2x4R8K2dGJ+MgF5Lw7JiB6S3TD9Ilc8S76L4Z37KTrydXxVK8J1jOO6dQPBKVFUwxRSqueAabLsmLdQ6rYlPxq7I3deyU+DruGZaQO4GSeL6EJvSKJ6mq4q6IUc0eOkqLQ1Mtv6mZ8CQfPToyartqe0ec/5cpK+Tu4ItZbIOdnAsIJnrVCdKqxQDwIkF3uoqcZIsSEgefgK33ncLtz2ba+TK19H9vgFGt4xawsv7ngS1kUuyHgkrMamLEnWdNNCFhGxcuXfU+qCAlw84kldgnqRwzk1mUUdnChpCeGndOQtkKKRuS1WCc444pWwx3u0M9RUnYEYuJoeJi5g7XB2Z/nKZiRIj4sdhdVK/apehI8s7MVkNAkfJIbiBbVLUJbthhxKoaSC3Dv5KLfaiLLt3davYibs3Y0voAZVPqy0Onm9RItIrwK9/XCko=
install:
- python -m pip install twine cibuildwheel==1.1.0
script:
- python -m cibuildwheel --output-dir wheelhouse
after_success:
- if [[ $TRAVIS_TAG ]]; then python -m twine upload wheelhouse/*.whl; fi
